/**
 * ChessGamesAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChessGameDto { 
    white?: string | null;
    black?: string | null;
    result?: string | null;
    date?: string | null;
    game?: string | null;
    site?: string | null;
    event?: string | null;
    round?: string | null;
}

